Repository nimblehq/ic-flutter-taher-toby, pull requests merged in 2023-05, with the labels that each got.

#80 [#32][#33] [UI] [Integrate] As a user, I can answer with a NPS
  lib/api/response/answer_response.dart
  lib/api/response/question_response.dart
  lib/l10n/app_en.arb
  lib/model/answer_model.dart
  lib/model/question_model.dart
  lib/theme/app_dimensions.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/widget/form_survey_answer_nps.dart
  lib/ui/form/widget/form_survey_question_page.dart
  test/ui/form/form_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, priority : medium, @0.5.0

#77 [#26] [#27] [UI] [Integrate] As a user, I can answer with an emoji rating
  lib/theme/app_dimensions.dart
  lib/ui/form/widget/form_survey_answer_emoji.dart
  lib/ui/form/widget/form_survey_question_page.dart
Labels: type : feature, priority : medium, @0.5.0

#81 [#38] [#39] [UI] [Integrate] As a user, I can answer with a text area
  lib/l10n/app_en.arb
  lib/theme/app_dimensions.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/widget/form_survey_answer_textarea.dart
  lib/ui/form/widget/form_survey_question_page.dart
Labels: type : feature, priority : medium, @0.5.0

#82 [#30][#31] As a user, I can answer with a dropdown
  lib/theme/app_dimensions.dart
  lib/ui/form/widget/form_survey_answer_dropdown.dart
  lib/ui/form/widget/form_survey_question_page.dart
Labels: type : feature, priority : medium, @0.6.0

#87 [Chore] Bump version to 0.6.0
  pubspec.yaml
Labels: type : chore, priority : medium, @0.6.0

#83 [#34][#35] As a user, I can answer with a multiple choice
  lib/theme/app_dimensions.dart
  lib/ui/form/widget/form_survey_answer_multi_choice.dart
  lib/ui/form/widget/form_survey_question_page.dart
Labels: type : feature, priority : medium, @0.6.0

#85 [#36][#37] [UI] [Integrate] As a user, I can answer with text fields
  lib/ui/form/widget/form_survey_answer_text_field.dart
  lib/ui/form/widget/form_survey_question_page.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/custom_text_field.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, priority : medium, @0.6.0

#88 [#40] [Backend] As a user, I can submit the form
  lib/api/repository/survey_repository.dart
  lib/api/request/submit_survey_answer_request.dart
  lib/api/request/submit_survey_question_request.dart
  lib/api/request/submit_survey_request.dart
  lib/api/survey_service.dart
  lib/model/submit_survey_question_model.dart
  lib/usecases/submit_survey_use_case.dart
  test/api/repository/survey_repository_test.dart
  test/usecases/submit_survey_use_case_test.dart
Labels: type : feature, priority : medium, @0.6.0

#89 [#42] Add UI for survey completion page
  assets/animations/survey_completion.json
  lib/l10n/app_en.arb
  lib/theme/app_dimensions.dart
  lib/ui/form/widget/form_survey_completion_page.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, priority : medium, @0.6.0

#90 [#41] [Integrate] As a user, I can submit the form
  lib/api/request/submit_survey_answer_request.dart
  lib/app_navigator.dart
  lib/model/submit_survey_question_model.dart
  lib/model/survey_details_model.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/form_state.dart
  lib/ui/form/form_view_model.dart
  lib/ui/form/widget/form_survey_answer_dropdown.dart
  lib/ui/form/widget/form_survey_answer_emoji.dart
  lib/ui/form/widget/form_survey_answer_multi_choice.dart
  lib/ui/form/widget/form_survey_answer_nps.dart
  lib/ui/form/widget/form_survey_answer_smiley.dart
  lib/ui/form/widget/form_survey_answer_text_field.dart
  lib/ui/form/widget/form_survey_answer_textarea.dart
  lib/ui/form/widget/form_survey_question_page.dart
  lib/ui/widget/custom_text_field.dart
  test/mocks/generate_mocks.dart
  test/ui/form/form_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, priority : medium, @0.6.0

#93 [#43] [Integrate] As a user, I can see the "Thank You" animation
  lib/app_navigator.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/form_state.dart
  lib/ui/form/form_view_model.dart
  lib/ui/form/widget/form_survey_completion_page.dart
  test/ui/form/form_view_model_test.dart
Labels: type : feature, priority : medium, @0.6.0

#94 [#91] [Test] As a developer, I can run automated UI tests for home screen
  integration_test/app_test.dart
  lib/constant/widget_keys.dart
  lib/ui/form/form_screen.dart
  lib/ui/widget/next_button.dart
Labels: type : chore, priority : medium, @0.6.0

#95 [#92] [Test] As a developer, I can run automated UI tests for form screen
  README.md
  android/gradle.properties
  integration_test/app_test.dart
  integration_test/my_home_page_test.dart
  integration_test/real_app_test.dart
  lib/constant/widget_keys.dart
  lib/ui/form/form_screen.dart
  lib/ui/widget/next_button.dart
Labels: type : chore, priority : medium, @0.6.0

#96 Release 0.6.0
  .github/workflows/test.yml
  README.md
  android/gradle.properties
  assets/animations/survey_completion.json
  integration_test/app_test.dart
  integration_test/my_home_page_test.dart
  integration_test/real_app_test.dart
  lib/api/repository/survey_repository.dart
  lib/api/request/submit_survey_answer_request.dart
  lib/api/request/submit_survey_question_request.dart
  lib/api/request/submit_survey_request.dart
  lib/api/survey_service.dart
  lib/constant/widget_keys.dart
  lib/l10n/app_en.arb
  lib/model/submit_survey_question_model.dart
  lib/model/survey_details_model.dart
  lib/theme/app_dimensions.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/form_state.dart
  lib/ui/form/form_view_model.dart
  lib/ui/form/widget/form_survey_answer_dropdown.dart
  lib/ui/form/widget/form_survey_answer_emoji.dart
  lib/ui/form/widget/form_survey_answer_multi_choice.dart
  lib/ui/form/widget/form_survey_answer_nps.dart
  lib/ui/form/widget/form_survey_answer_smiley.dart
  lib/ui/form/widget/form_survey_answer_text_field.dart
  lib/ui/form/widget/form_survey_answer_textarea.dart
  lib/ui/form/widget/form_survey_completion_page.dart
  lib/ui/form/widget/form_survey_question_page.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/custom_text_field.dart
  lib/ui/widget/next_button.dart
  lib/usecases/submit_survey_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/survey_repository_test.dart
  test/mocks/generate_mocks.dart
  test/ui/form/form_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
  test/usecases/submit_survey_use_case_test.dart
Labels: type : release, priority : medium, @0.6.0
