Repository nimblehq/ic-flutter-taher-toby, pull requests merged in 2023-04, with the labels that each got.

#51 [#4] Set up CD for iOS (TestFlight)
  .github/workflows/ios_deploy_production.yml
  .github/workflows/ios_deploy_staging.yml
  .github/workflows/ios_deploy_to_app_store.yml
  .github/workflows/ios_deploy_to_testflight.yml
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Fastfile
  ios/fastlane/Gymfile
  ios/fastlane/Matchfile
Labels: type : chore, priority : medium, @0.2.0

#54 [#11] [UI] As a user, I can see the list of surveys
  assets/images/dummy_avatar.png
  assets/images/dummy_background.png
  integration_test/my_home_page_test.dart
  lib/app_navigator.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/widget/home_header.dart
  lib/ui/home/widget/home_survey_page.dart
  lib/ui/home/widget/home_survey_page_indicator.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/ui/widget/dimmed_background.dart
  lib/ui/widget/next_button.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, priority : medium, @0.2.0

#55 [#12] [Backend] As a user, I can see the list of surveys
  lib/api/api_service.dart
  lib/api/repository/credential_repository.dart
  lib/api/repository/survey_repository.dart
  lib/api/response/decoder/response_decoder.dart
  lib/api/response/survey_response.dart
  lib/api/response/surveys_response.dart
  lib/api/survey_service.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/network_module.dart
  lib/di/provider/dio_provider.dart
  lib/model/response/user_response.dart
  lib/model/survey_model.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/get_surveys_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/credential_repository_test.dart
  test/api/repository/survey_repository_test.dart
  test/mock_responses/surveys.json
  test/mocks/generate_mocks.dart
  test/usecases/get_surveys_use_case_test.dart
  test/utils/file_utils.dart
Labels: type : feature, priority : medium, @0.2.0

#56 [#13] [Integrate] As a user, I can see the list of surveys
  assets/images/dummy_background.png
  lib/api/response/survey_response.dart
  lib/di/interceptor/app_interceptor.dart
  lib/main.dart
  lib/model/survey_model.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/widget/home_survey_page.dart
  lib/ui/home/widget/home_survey_page_indicator.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/ui/widget/dimmed_background.dart
  lib/ui/widget/snack_bar.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/ui/home/home_view_model_test.dart
  test/usecases/get_surveys_use_case_test.dart
Labels: type : feature, priority : medium, @0.2.0

#57 [#16][#17] [UI][Integrate] As a user, I can see the loading screen for surveys
  lib/theme/app_dimensions.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/widget/home_header.dart
  lib/ui/home/widget/home_skeleton_loading.dart
  pubspec.lock
  pubspec.yaml
  test/ui/home/home_view_model_test.dart
Labels: type : feature, priority : medium, @0.2.0

#59 [#7] [UI] As a user, I can see the splash screen for log-in
  assets/images/splash_background.png
  assets/images/splash_logo_white.png
  lib/app_navigator.dart
  lib/main.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/dimmed_background.dart
Labels: type : feature, priority : medium, @0.3.0

#61 [Release] 0.2.0
  .github/workflows/ios_deploy_production.yml
  .github/workflows/ios_deploy_staging.yml
  .github/workflows/ios_deploy_to_app_store.yml
  .github/workflows/ios_deploy_to_testflight.yml
  assets/images/dummy_avatar.png
  assets/images/splash_background.png
  assets/images/splash_logo_white.png
  integration_test/my_home_page_test.dart
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Fastfile
  ios/fastlane/Gymfile
  ios/fastlane/Matchfile
  lib/api/api_service.dart
  lib/api/repository/credential_repository.dart
  lib/api/repository/survey_repository.dart
  lib/api/response/decoder/response_decoder.dart
  lib/api/response/survey_response.dart
  lib/api/response/surveys_response.dart
  lib/api/survey_service.dart
  lib/app_navigator.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/network_module.dart
  lib/di/provider/dio_provider.dart
  lib/l10n/app_en.arb
  lib/l10n/app_th.arb
  lib/l10n/app_vi.arb
  lib/main.dart
  lib/model/response/user_response.dart
  lib/model/survey_model.dart
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/widget/home_header.dart
  lib/ui/home/widget/home_skeleton_loading.dart
  lib/ui/home/widget/home_survey_page.dart
  lib/ui/home/widget/home_survey_page_indicator.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/ui/login/login_screen.dart
  lib/ui/widget/dimmed_background.dart
  lib/ui/widget/next_button.dart
  lib/ui/widget/snack_bar.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/get_surveys_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/credential_repository_test.dart
  test/api/repository/survey_repository_test.dart
  test/mock_responses/surveys.json
  test/mocks/generate_mocks.dart
  test/ui/home/home_view_model_test.dart
  test/usecases/get_surveys_use_case_test.dart
  test/utils/file_utils.dart
Labels: priority : high, type : release, @0.2.0

#62 [Chore] Bump version to 0.3.0
  pubspec.yaml
Labels: type : chore, priority : medium, @0.3.0

#58 [#14] [Integrate] As a user, I can cache the list of surveys
  lib/api/repository/survey_repository.dart
  lib/database/hive.dart
  lib/database/survey_storage.dart
  lib/di/di.dart
  lib/di/module/storage_module.dart
  lib/main.dart
  lib/model/survey_model.dart
  lib/ui/home/home_screen.dart
  lib/ui/home/home_state.dart
  lib/ui/home/home_view_model.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/usecases/base/base_use_case.dart
  lib/usecases/get_cached_surveys_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/survey_repository_test.dart
  test/mocks/generate_mocks.dart
  test/ui/home/home_view_model_test.dart
  test/usecases/get_cached_surveys_use_case_test.dart
Labels: type : feature, priority : medium, @0.3.0

#60 [#8] [UI] As a user, I can log in with email and password
  lib/l10n/app_en.arb
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/login/login_screen.dart
Labels: type : chore, type : feature, @0.3.0

#65 [#9] [Backend] As a user, I can log in with email and password
  .env.sample
  ios/Podfile.lock
  lib/api/repository/authentication_repository.dart
  lib/api/request/login_request.dart
  lib/api/response/decoder/response_decoder.dart
  lib/api/response/login_response.dart
  lib/api/service/authentication_service.dart
  lib/di/module/network_module.dart
  lib/env.dart
  lib/model/login_model.dart
  lib/ui/login/login_screen.dart
  lib/usecases/log_in_use_case.dart
  test/api/repository/authentication_repository_test.dart
  test/mock_responses/login_data.json
  test/mocks/generate_mocks.dart
  test/usecases/log_in_use_case_test.dart
Labels: type : feature, priority : medium, @0.3.0

#64 [#21] [UI] As a user, I can see the survey details
  assets/images/nimble_logo.png
  lib/app_navigator.dart
  lib/l10n/app_en.arb
  lib/theme/app_colors.dart
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/widget/form_survey_detail_page.dart
  lib/ui/form/widget/form_survey_question_page.dart
  lib/ui/home/widget/home_survey_page.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/ui/second/second_screen.dart
Labels: type : feature, priority : medium, @0.3.0

#66 [#22] [Backend] As a user, I can see the survey details
  lib/api/repository/survey_repository.dart
  lib/api/response/survey_details_response.dart
  lib/api/survey_service.dart
  lib/app_navigator.dart
  lib/model/survey_details_model.dart
  lib/ui/form/form_screen.dart
  lib/ui/home/widget/home_survey_page_viewer.dart
  lib/usecases/get_survey_details_use_case.dart
  test/api/repository/survey_repository_test.dart
  test/mock_responses/survey_details.json
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, priority : medium, @0.3.0

#67 [#23] [Integrate] As a user, I can see the survey details
  lib/api/response/survey_details_response.dart
  lib/theme/app_theme.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/form_state.dart
  lib/ui/form/form_view_model.dart
  lib/ui/form/widget/form_survey_detail_page.dart
  test/mocks/generate_mocks.dart
  test/ui/form/form_view_model_test.dart
Labels: type : feature, priority : medium, @0.4.0

#71 [#24] [UI] As a user, I can see the survey questions
  lib/app_navigator.dart
  lib/l10n/app_en.arb
  lib/theme/app_colors.dart
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/widget/form_survey_detail_page.dart
  lib/ui/form/widget/form_survey_question_page.dart
Labels: type : feature, priority : medium, @0.4.0

#70 [#10] [Integrate] As a user, I can log in with email and password
  ios/Podfile.lock
  lib/app_navigator.dart
  lib/database/secure_storage.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/storage_module.dart
  lib/di/provider/dio_provider.dart
  lib/l10n/app_en.arb
  lib/ui/login/login_screen.dart
  lib/ui/login/login_state.dart
  lib/ui/login/login_view_model.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/log_in_use_case.dart
  lib/usecases/store_auth_token_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/ui/login/login_view_model_test.dart
  test/usecases/store_auth_token_use_case_test.dart
Labels: type : feature, priority : medium, @0.4.0

#72 [#25] [Integrate] As a user, I can see the survey questions
  lib/api/response/question_response.dart
  lib/api/response/survey_details_response.dart
  lib/model/question_model.dart
  lib/model/survey_details_model.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/widget/form_survey_question_page.dart
  test/ui/form/form_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, priority : medium, @0.4.0

#74 [#28][#29] [UI] & [Integrate] As a user, I can answer with a smiley rating
  lib/api/response/question_response.dart
  lib/model/question_model.dart
  lib/model/survey_details_model.dart
  lib/theme/app_colors.dart
  lib/theme/app_dimensions.dart
  lib/ui/form/widget/form_survey_answer_smiley.dart
  lib/ui/form/widget/form_survey_question_page.dart
  test/ui/form/form_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
Labels: type : feature, priority : medium, @0.4.0

#73 [#18] [Integrate] As a cached user, I don't need to log in again
  lib/app_navigator.dart
  lib/ui/app_starter/app_starter_screen.dart
  lib/ui/app_starter/app_starter_state.dart
  lib/ui/app_starter/app_starter_view_model.dart
  lib/ui/login/login_screen.dart
  lib/usecases/is_logged_in_use_case.dart
  lib/usecases/store_auth_token_use_case.dart
  test/mocks/generate_mocks.dart
  test/ui/app_starter/app_starter_view_model_test.dart
  test/usecases/is_logged_in_use_case_test.dart
Labels: type : feature, priority : medium, @0.4.0

#76 [Bug] Fix back button navigates to white screen
  lib/app_navigator.dart
Labels: type : bug, priority : medium, @0.5.0

#78 [Release] 0.4.0
  ios/Podfile.lock
  lib/api/response/question_response.dart
  lib/api/response/survey_details_response.dart
  lib/app_navigator.dart
  lib/database/secure_storage.dart
  lib/di/interceptor/app_interceptor.dart
  lib/di/module/storage_module.dart
  lib/di/provider/dio_provider.dart
  lib/l10n/app_en.arb
  lib/model/question_model.dart
  lib/model/survey_details_model.dart
  lib/theme/app_colors.dart
  lib/theme/app_dimensions.dart
  lib/theme/app_theme.dart
  lib/ui/app_starter/app_starter_screen.dart
  lib/ui/app_starter/app_starter_state.dart
  lib/ui/app_starter/app_starter_view_model.dart
  lib/ui/form/form_screen.dart
  lib/ui/form/form_state.dart
  lib/ui/form/form_view_model.dart
  lib/ui/form/widget/form_survey_answer_smiley.dart
  lib/ui/form/widget/form_survey_detail_page.dart
  lib/ui/form/widget/form_survey_question_page.dart
  lib/ui/login/login_screen.dart
  lib/ui/login/login_state.dart
  lib/ui/login/login_view_model.dart
  lib/usecases/base/use_case_result.dart
  lib/usecases/is_logged_in_use_case.dart
  lib/usecases/log_in_use_case.dart
  lib/usecases/store_auth_token_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/mocks/generate_mocks.dart
  test/ui/app_starter/app_starter_view_model_test.dart
  test/ui/form/form_view_model_test.dart
  test/ui/login/login_view_model_test.dart
  test/usecases/get_survey_details_use_case_test.dart
  test/usecases/is_logged_in_use_case_test.dart
  test/usecases/store_auth_token_use_case_test.dart
Labels: type : release, priority : medium, @0.4.0

#79 [Chore] Bump version to 0.5.0
  pubspec.yaml
Labels: type : chore, priority : medium, @0.5.0
